config/routes.rb
Rails.application.routes.draw do
  get "todos/index"
  put "todos/:id", to: "todos#update"
  get "todos/new", to: "todos#new", as: "new_todo"
  post "todos", to: "todos#create"

  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
  get "up" => "rails/health#show", as: :rails_health_check

  # Render dynamic PWA files from app/views/pwa/* (remember to link manifest in application.html.erb)
  # get "manifest" => "rails/pwa#manifest", as: :pwa_manifest
  # get "service-worker" => "rails/pwa#service_worker", as: :pwa_service_worker

  # Defines the root path route ("/")
  root "todos#index"
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/todo.rb
class Todo < ApplicationRecord
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Only allow modern browsers supporting webp images, web push, badges, import maps, CSS nesting, and CSS :has.
  allow_browser versions: :modern

  # Changes to the importmap will invalidate the etag for HTML responses
  stale_when_importmap_changes
end

app/controllers/todos_controller.rb
class TodosController < ApplicationController
  def index
    @todos = Todo.all
  end

  def update
    @todo = Todo.find(params[:id])

    respond_to do |format|
      if @todo.update(todo_params)
        format.turbo_stream { }
      end
    end
  end

  def new
    @todo = Todo.new
  end

  def create
    todo = Todo.create(todo_params)

    redirect_to todos_index_path
  end

  private

    def todo_params
      params.expect(todo: [ :title, :is_completed ])
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/todos_helper.rb
module TodosHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title><%= content_for(:title) || "Kan Todo App Rails" %></title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <meta name="apple-mobile-web-app-capable" content="yes">
    <meta name="application-name" content="Kan Todo App Rails">
    <meta name="mobile-web-app-capable" content="yes">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= yield :head %>

    <%# Enable PWA manifest for installable apps (make sure to enable in config/routes.rb too!) %>
    <%#= tag.link rel: "manifest", href: pwa_manifest_path(format: :json) %>

    <link rel="icon" href="/icon.png" type="image/png">
    <link rel="icon" href="/icon.svg" type="image/svg+xml">
    <link rel="apple-touch-icon" href="/icon.png">

    <%# Includes all stylesheet files in app/assets/stylesheets %>
    <%= stylesheet_link_tag :app, "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>

  <body>
    <main class="container mx-auto mt-28 px-5 flex justify-center">
      <%= yield %>
    </main>
  </body>
</html>

app/views/todos/_todo.html.erb
  <div class="p-2 rounded-lg <%= todo.is_completed ? "bg-green-500" : "bg-gray-200" %> flex items-center" id="<%= dom_id(todo) %>">
    <%= check_box_tag "completed", true, todo.is_completed, id: dom_id(todo, :checkbox),
        class: "mr-2 w-5 h-5",
        data: { controller: "checkbox", action: "change->checkbox#update", checkbox_url_value: url_for(controller: "todos", action: "update", id: todo.id) } %>
    <span><%= todo.title %></span>
  </div>

app/views/todos/index.html.erb
<div class="flex flex-col w-1/3">
  <div class="flex justify-between items-end">
    <h1 class="text-3xl">To-Do</h1>
    <%= link_to "New To-Do", new_todo_path,
        class: "inline-block px-4 py-2 rounded-lg bg-blue-600 text-white hover:bg-blue-700" %>
  </div>
  <div class="flex flex-col mt-4 gap-2">
    <% @todos.each do |todo| %>
      <%= render todo %>
    <% end %>
  </div>
</div>

app/views/todos/new.html.erb
<div class="flex flex-col w-1/3">
  <h1 class="text-3xl">New To-Do</h1>
  <%= form_with model: @todo, class: "flex flex-col mt-4 gap-4" do |f| %>
    <div class="field flex flex-col gap-2">
      <%= f.label :title, class: "font-medium" %>
      <%= f.text_field :title, class: "w-full border px-4 py-2 rounded-lg focus:outline-none focus:ring-2 focus:ring-blue-500" %>
    </div>
    <div class="actions flex justify-between">
      <%= link_to "Back", todos_index_path,
          class: "inline-block px-3 py-2 rounded-lg bg-gray-100 hover:bg-gray-200" %>
      <%= f.submit "Create Todo", class: "px-4 py-2 rounded-lg bg-blue-600 text-white font-medium hover:bg-blue-700 active:bg-blue-800" %>
    </div>
  <% end %>
</div>

app/views/todos/update.turbo_stream.erb
<%= turbo_stream.replace dom_id(@todo),
    partial: "todos/todo",
    locals: { todo: @todo } %>